apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: postgres-v1
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: postgres-cluster
    role: primary
  ports:
    - port: 5432
      targetPort: 5432