apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-rw
  namespace: podtgresql-v1
spec:
  type: ClusterIP
  selector:
    cnpg.io/cluster: pg-cluster
    role: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432